//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MarjoAndDaniel.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RsvpEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RsvpEntities object using the connection string found in the 'RsvpEntities' section of the application configuration file.
        /// </summary>
        public RsvpEntities() : base("name=RsvpEntities", "RsvpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RsvpEntities object.
        /// </summary>
        public RsvpEntities(string connectionString) : base(connectionString, "RsvpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RsvpEntities object.
        /// </summary>
        public RsvpEntities(EntityConnection connection) : base(connection, "RsvpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RSVP> RSVPs
        {
            get
            {
                if ((_RSVPs == null))
                {
                    _RSVPs = base.CreateObjectSet<RSVP>("RSVPs");
                }
                return _RSVPs;
            }
        }
        private ObjectSet<RSVP> _RSVPs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RSVPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRSVPs(RSVP rSVP)
        {
            base.AddObject("RSVPs", rSVP);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeedModel", Name="RSVP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RSVP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RSVP object.
        /// </summary>
        /// <param name="ix">Initial value of the Ix property.</param>
        public static RSVP CreateRSVP(global::System.Int32 ix)
        {
            RSVP rSVP = new RSVP();
            rSVP.Ix = ix;
            return rSVP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ix
        {
            get
            {
                return _Ix;
            }
            set
            {
                if (_Ix != value)
                {
                    OnIxChanging(value);
                    ReportPropertyChanging("Ix");
                    _Ix = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ix");
                    OnIxChanged();
                }
            }
        }
        private global::System.Int32 _Ix;
        partial void OnIxChanging(global::System.Int32 value);
        partial void OnIxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Guest1Name
        {
            get
            {
                return _Guest1Name;
            }
            set
            {
                OnGuest1NameChanging(value);
                ReportPropertyChanging("Guest1Name");
                _Guest1Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Guest1Name");
                OnGuest1NameChanged();
            }
        }
        private global::System.String _Guest1Name;
        partial void OnGuest1NameChanging(global::System.String value);
        partial void OnGuest1NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Guest1Editable
        {
            get
            {
                return _Guest1Editable;
            }
            set
            {
                OnGuest1EditableChanging(value);
                ReportPropertyChanging("Guest1Editable");
                _Guest1Editable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Guest1Editable");
                OnGuest1EditableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Guest1Editable;
        partial void OnGuest1EditableChanging(Nullable<global::System.Boolean> value);
        partial void OnGuest1EditableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Guest2Name
        {
            get
            {
                return _Guest2Name;
            }
            set
            {
                OnGuest2NameChanging(value);
                ReportPropertyChanging("Guest2Name");
                _Guest2Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Guest2Name");
                OnGuest2NameChanged();
            }
        }
        private global::System.String _Guest2Name;
        partial void OnGuest2NameChanging(global::System.String value);
        partial void OnGuest2NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Guest2Editable
        {
            get
            {
                return _Guest2Editable;
            }
            set
            {
                OnGuest2EditableChanging(value);
                ReportPropertyChanging("Guest2Editable");
                _Guest2Editable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Guest2Editable");
                OnGuest2EditableChanged();
            }
        }
        private Nullable<global::System.Boolean> _Guest2Editable;
        partial void OnGuest2EditableChanging(Nullable<global::System.Boolean> value);
        partial void OnGuest2EditableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AllowedPlusOne
        {
            get
            {
                return _AllowedPlusOne;
            }
            set
            {
                OnAllowedPlusOneChanging(value);
                ReportPropertyChanging("AllowedPlusOne");
                _AllowedPlusOne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowedPlusOne");
                OnAllowedPlusOneChanged();
            }
        }
        private Nullable<global::System.Boolean> _AllowedPlusOne;
        partial void OnAllowedPlusOneChanging(Nullable<global::System.Boolean> value);
        partial void OnAllowedPlusOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GuestPrefilled
        {
            get
            {
                return _GuestPrefilled;
            }
            set
            {
                OnGuestPrefilledChanging(value);
                ReportPropertyChanging("GuestPrefilled");
                _GuestPrefilled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GuestPrefilled");
                OnGuestPrefilledChanged();
            }
        }
        private Nullable<global::System.Boolean> _GuestPrefilled;
        partial void OnGuestPrefilledChanging(Nullable<global::System.Boolean> value);
        partial void OnGuestPrefilledChanged();

        #endregion
    
    }

    #endregion
    
}
